[tool.poetry]
name = "trustlens-py"
version = "0.1.0"
description = "Python client SDK for TrustLens API"
authors = ["TrustLens Team <team@trustlens.ai>"]
readme = "README.md"
packages = [{include = "trustlens"}]
homepage = "https://trustlens.ai"
repository = "https://github.com/trustlens/trustlens"
keywords = ["manipulation-detection", "bias-detection", "api-client", "sdk"]

[tool.poetry.dependencies]
python = "^3.10"
httpx = "^0.25.0"
pydantic = "^2.5.0"
typing-extensions = "^4.8.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-asyncio = "^0.21.0"
black = "^23.9.0"
isort = "^5.12.0"
flake8 = "^6.1.0"
mypy = "^1.6.0"
pytest-cov = "^4.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py310']

[tool.isort]
profile = "black"
line_length = 88

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "--cov=trustlens --cov-report=html --cov-report=term-missing"